version: '3'
services:

  majordomo:
    build: ./app-conf/debian/
    container_name: majordomo_${PROJECT_NAME}_majordomo
    ports:
      - ${MAJORDOMO_NGINX_PORT}:80
      - ${MAJORDOMO_UI_PORT}:8001
    networks:
      majordomo:
    volumes:
      - './app:/var/www/html'
      - './zigbee2mqtt/log:/opt/zigbee2mqtt/data/log'
    links:
      - mysql

  mysql:
    image: linuxserver/mariadb
    container_name: majordomo_${PROJECT_NAME}_mysql
    networks:
      majordomo:
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF
    restart: always

networks:
  majordomo:
    external:
      true
